azs:
- name: z1
  cloud_properties: {availability_zone: us-west-2a}

vm_types:
- name: medium
  cloud_properties:
    instance_type: m3.large
    ephemeral_disk: {size: 10000, type: gp2}
- name: mediumworker
  cloud_properties:
    instance_type: m4.2xlarge
    ephemeral_disk: {size: 300000, type: gp2}

vm_extensions:
- name: pub-lbs
  cloud_properties:
    elbs: [gpdblangu-LoadBala-FJVVEEAVXH6U]
  
disk_types:
- name: small
  disk_size: 5000
  cloud_properties: {type: gp2}
- name: large
  disk_size: 50_000
  cloud_properties: {type: gp2}

networks:
- name: private
  type: manual
  subnets:
  - range: 10.0.0.0/24
    reserved: [10.0.0.0-10.0.0.10]
    gateway: 10.0.0.1
    az: z1
    dns: [10.0.0.2]
    cloud_properties:
      subnet: subnet-a7a612d1
      security_groups: [sg-5f67ca39]
- name: public
  type: vip

compilation:
  workers: 1
  reuse_compilation_vms: true
  az: z1
  vm_type: medium
  network: private